name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Install latest npm
        run: npm i -g npm@latest
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Update ffmpeg peer dependency version
        run: |
          node -e 'const fs = require("node:fs"); const rootPkg = JSON.parse(fs.readFileSync("package.json", "utf8")); const ffmpegPkgPath = "packages/ffmpeg/package.json"; const ffmpegPkg = JSON.parse(fs.readFileSync(ffmpegPkgPath, "utf8")); ffmpegPkg.peerDependencies["@byjonas/ffmpeg-binaries"] = rootPkg.version; fs.writeFileSync(ffmpegPkgPath, JSON.stringify(ffmpegPkg, null, 2) + "\n");'
      - name: Build packages
        run: pnpm -w run build
      - name: Publish packages
        run: |
          cd packages/ffmpeg-binaries
          npm publish --provenance --access public

          cd ../ffmpeg
          npm publish --provenance --access public
